### ISSUE TITLE
Some issues on MMClassification training in 1.x version

### ISSUE THREAD

**Issue by franklegolasyoung** [wangruohui/sjtu-openmmlab-tutorial#1]
Hi, I saw your's tutorial video of the 0.x version MMClassification, which is clear and helpful. However, as I try training with my own dataset as in the tutorial, I find now the provided models configs are changed, and it could not work by just changing those few parameters as in the video. I would be greatly thankful if you could provide some tutorials or some updated docs of the 1.x version MMClassification training with my own dataset.

**Comment by wangruohui** [comment]
Thanks for your attention. Actually, we are updating tutorials on new versions. Maybe you can see that in days.
